### PR TITLE
Project 1 Work 2/5

### PR DESCRIPTION
**Pull request by dmcnulty27**
@peihongx 
@Finn1928 
@giacomodecolle 
@katiejohnso

### CODE REVIEW

**Comment by johnbeve** [comment]
Hi there,
Opening a pull request to merge in my repository is what we'll be doing next week. This week, I'd like you to open a pull request in your _own_ repository, then assign it to at least two of your peers from class. You'll all then review your updates, and once your reviewers give you the green light, you'll merge your changes to your branch, then open a pull request for me to review.
@Finn1928, you seem to have figured out the workflow; perhaps you can give @dmcnulty27 a hand here? 
-John

**Comment by dmcnulty27** [comment]
Drat. I thought i did this properly. I will attempt again

**Comment by Finn1928** [comment]
Hi Dr. Beverley,
Sorry to bother you. I'm not sure how to do this properly. I'm trying to
open a pull request in my own repository, but I can't figure out how to do
it. I'm attaching an image of what it looks like when I'm in my own project
and click to create a pull request. Where should I go from here?
Best,
-Finn Wilson

**Comment by johnbeve** [comment]
@Finn1928 Happy to help; where is the image you referenced? I'm attaching an image of what it looks like when I make a commit in my repo: 

Screen Shot 2023-02-05 at 12 21 45 PM

At the bottom you'll see options for committing to your main branch or creating a new branch and opening a pull request. Select the second option. When you do, you'll be taken to a screen that looks like this: 

Screen Shot 2023-02-05 at 12 25 42 PM

On the bottom right of the screen, you'll see a place to open a pull request.

**Comment by Finn1928** [comment]
Hi Dr. Beverley,
I sent this as an email. Apparently doing that also makes the message show
up in github. The image is an attachment to the email. It doesn't appear in
the github message. I think I created a new branch to my project, but it
didn't take me to a page that looks like that. It sent me to one that looks
like the image I'm attaching to this email.
-Finn

**Comment by johnbeve** [comment]
@Finn1928 Afraid there's no attachment in the emails to see. You can drag and drop screenshots in the text field (where I'm typing right now). That'll be the easiest thing to do, I think.

**Comment by Finn1928** [comment]
I'm not sure why the images aren't showing up in your email. I can see that they were attached, and they're visible in the email for me. Are you able to see these ones? Also, I'm adding a third image of what might be a request sent to 2 people?

pull request
pull request 2
pull request 3

**Pull request closed without merging**
