### PR TITLE
Jiemingy project 1

### PR DESCRIPTION
**Pull request by Jiemingy**

### CODE REVIEW

**Comment by johnbeve** [comment]
Hi @Jiemingy 
You skipped a step unfortunately. You should open a pull request on your local repo and assign two reviewers this week. Next week you'll push to me for review. See @Finn1928's repo for what this is supposed to look like.

**Comment by Jiemingy** [comment]
Hi @johnbeve Do I need to create a new branch and start a pull request? I am lost there. It doesn't let me create a new branch. I must mistake somewhere.
Screenshot 2023-02-05 at 9 09 20 PM

**Comment by johnbeve** [comment]
@Jiemingy You'll need to make some change to the file, e.g. add a space to the last line of the file, so that there is something to commit. Typically, you'll open a pull request when you make changes so this issue doesn't come up :)

**Comment by Jiemingy** [comment]
Thank you @johnbeve Is it right that I click "propose changes" button? It seems not bring me to a new branch.
Screenshot 2023-02-05 at 9 28 06 PM

**Comment by johnbeve** [comment]
No problem @Jiemingy. Yessir hit that button, since the change you're proposing is to "create a new branch for this commit and start a pull request."

**Comment by Jiemingy** [comment]
@johnbeve then it goes to the below. Should I make a pull request on the upper bar? 

Screenshot 2023-02-05 at 9 45 41 PM

**Comment by Jiemingy** [comment]
Hi @johnbeve, I hit the "Create pull request" in the below first step, then it goes to the below second step. However, there is no reviewer I can choose. Did I make mistake somewhere? 

Screenshot 2023-02-05 at 10 10 17 PM
Screenshot 2023-02-05 at 10 10 59 PM

**Pull request closed without merging**
