### PR TITLE
Finn Assign 1 Pull Request

### PR DESCRIPTION
**Pull request by Finn1928**

### CODE REVIEW

**Comment by johnbeve** [comment]
Hi Finn, 
Opening a pull request to merge in my repository is what we'll be doing next week. This week, I'd like you to open a pull request in your own repository, then assign it to at least two of your peers from class. You'll all then review your updates, and once your reviewers give you the green light, you'll merge your changes to your branch, then open a pull request for me to review. 
Does that make sense? 
-John

**Comment by dmcnulty27** [comment]
Osiyo John,
Please don't feel it necessary to respond at such a late hour unless it is convenient for you. have 3 follow up questions to what Finn has done.

1. Does this project 1 need to be completed in full, that is every question having a response (or at least our first attempts) by Monday or will it be on going until the pull requests close on the 14th?
2. Should we commit to 2 classmates before class?
3. How do I put an image into github? The stackoverflow stuff I found was not very helpful. I know I can paste a link of some sorts but if I wanted to insert say, a diagram of a universe for question 7 how could this be achieved? Can it be achieved?

Wado,
Delaney
________________________________

**Comment by johnbeve** [comment]
Hi @dmcnulty27 
Always happy to respond if I'm able. 
1. Yep, every question should have an answer, that way your peers will have something to review for the upcoming week. I understand these initial responses might not be perfect; I'm actually expecting it :) 
2. Yes please. I don't mind if you end up changing the reviewers at some point; that happens often in the real world, as sometimes folks are too busy to review so others need to step in. 
3. Yeah, stackoverflow isn't always helpful...try this: https://www.seancdavis.com/posts/three-ways-to-add-image-to-github-readme/

**Comment by dmcnulty27** [comment]
Thank you so much!!

**Pull request closed without merging**
