### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by johnbeve**
@Finn1928 @dmcnulty27 @SydCo99 @jonathanvajda @giacomodecolle @oliviahobai @Arachnophobian @JaronJCheung @Jiemingy 

This is what happens when you open a branch on your own repo. Now I can create a pull request and tag folks to review it for my personal repo.

### CODE REVIEW

**Comment by dmcnulty27** [comment]
> @Finn1928 @dmcnulty27 @SydCo99 @jonathanvajda @giacomodecolle @oliviahobai @Arachnophobian @JaronJCheung @Jiemingy
> 
> This is what happens when you open a branch on your own repo. Now I can create a pull request and tag folks to review it for my personal repo.

Hi, John on my end from my own repo it will not let me click the button to commit to the main or to create a new branch. I hope that made sense I am attempting to attach a photo 
image

**Comment by johnbeve** [comment]
@dmcnulty27 Ah yes, you have to make some sort of change to the file or there won't be anything to commit or create a branch about. Just hit the spacebar after text in the file somewhere and the button will light up. 

FYI typically, you'll have made the changes to the README file, then instead of committing to your main branch, you would've opened another branch and created a pull request. The button would be illuminated in that case since you made changes. The reason we're running into the button not being illuminated here is because you've already committed the changes you want reviewed to the main branch. Hitting the spacebar somewhere in the file to allow for a commit is a bit of a workaround, but hey it works!

**Comment by dmcnulty27** [comment]
Am I getting closer?
image

**Comment by johnbeve** [comment]
@dmcnulty27 Looks like you opened a pull request! You can tag reviewers by using "@" followed by a username. You can make the tagging formal by looking to the right hand side of the screen in the pull request where it says "Assignees". The little wheel symbol will let you select from users to add to the pull request. Here's an image: 

Screen Shot 2023-02-05 at 12 54 46 PM

**Comment by dmcnulty27** [comment]
@johnbeve Waooo one success in the books! However, my assigning abilities are not a success yet. Suggestions? Thank you Thank you THANK YOU for your help!
image

**Comment by Jiemingy** [comment]
Should I make a pull request on my repo, tagging the reviewers - I thought when I make a pull request, my branch will merge with the main branch. 
_Jieming

**Comment by johnbeve** [comment]
@Jiemingy bro, don't be deleting my branches like that...

**Comment by johnbeve** [comment]
@dmcnulty27 Are you having trouble identifying usernames? Here are a few: 

Screen Shot 2023-02-05 at 9 01 11 PM

**Comment by dmcnulty27** [comment]
> @dmcnulty27 Are you having trouble identifying usernames? Here are a few: 
> 
> Screen Shot 2023-02-05 at 9 01 11 PM
> 

I got it! I was using the @ when trying to add contributors. Evidently a no go

**Pull request closed without merging**
