### PR TITLE
Hi

### PR DESCRIPTION
**Pull request by oliviahobai**

### CODE REVIEW

**Comment by dmcnulty27** [comment]
Looking good Oliva. Make sure you review An Introduction to Descriptive logic section 2 to help scoot you further along with Question 4 and review the slides from class, that will help.
Regarding Question 6 I would just tighten up the language an Existential Quantifier does not necessarily mean "at least one" it means closer "there is a thing that exists." I only suggest this because in logic the symbolism of at least one is very specific and I don't want the terms you're using now to confuse later. :) 
Regarding Question 9 You should link up with somebody who has strong derivation skills and we can help you through the derivation -- using that PDF from Slack will help familiarize you with the rules in derivations and then you can use a checker to make sure you are working through it properly!

**Comment by Finn1928** [comment]
Hi Olivia,

I believe question 2(c) is similar to 2(b) where you can say that it's a tautology, so equivalent to something like p∨~p.

For question 3, the answers don't look well-formed to me, unless it's using a system I'm just unfamiliar with (which is very possible). If it helps, for 3(a) I get ∃x∃y∃z(P(z,y)∧P(z,x)∧¬Fx∧x≠y∧x≠z∧z≠y), which says there's something that's a parent of 2 things that are not identical to each other or to the parent, and one of them is not female. I might be going overboard with the non-identity statements.

I unfortunately can't be much help with 4 and 5, since I'm having a difficult time understanding description logic. If this link works, Giacomo shared some information with me for question 4 that might also be helpful to you: https://github.com/Finn1928/PHI-696-Finn-/pull/2#pullrequestreview-1290330792

For 7, I drew a diagram of a universe with 2 objects. The first object was in the R relation to itself and the second object. The second object was only in the R relation to itself. I think this makes the first sentence false and the second true. I've been told Mermaid is a good tool for drawing graphs, but I don't know how to use it. So instead I just drew arrows for relations by typing "------>".

I'm including my answer to 9(a) as an example of a derivation. But I don't think this is the only way to do it, and it's certainly not the prettiest. Instead of using this system, you could try googling "DeMorgan's Theorem proofs". I think you'll find people doing it slightly different ways from me, and you can just copy what they do.
1. Show: ∀x∀y(¬(Px ∧ Qx) → (¬Px ∨ ¬Qx))
2. |	Show: ∀y(¬(Px ∧ Qx) → (¬Px ∨ ¬Qx))   |
3. |	|	Show: ¬(Px ∧ Qx) → (¬Px ∨ ¬Qx) |
4. |	|	|¬(Px ∧ Qx)		                    |||		Assumption CD
5. |	|	|	Show: (¬Px ∨ ¬Qx)              |||
6. |	|	|	|~(¬Px ∨ ¬Qx)	                   ||||		Assumption ID
7. |	|	|	|	Show: Px                     ||||				
8. |	|	|	|	|~Px	                          |||||		Assumption ID
9. |	|	|	|	|~Px V ~Qx                |||||		8, Addition
10.|	|	|	|	|______________________|||||		6, 9, ID
11.|	|	|	|	Show: Qx                    ||||
12.|	|	|	|	|~Qx	                  |||||		Assumption ID
13.|	|	|	|	|~Px V ~Qx                |||||		12, Addition
14.|	|	|	|	|______________________|||||		6, 13, ID
15.|	|	|	|	Px ∧ Qx	                   ||||		7, 11, Adjunction
16.|  |       |       |____________________________||||          4, 15, ID
17.|	|	|__________________________________|||		5, CD
18.|  |________________________________________||		3, UD
19.|__________________________________________|		2, UD

For 10, the primary difference I see is that the tree proofs always work by assuming that what you're trying to show is false and deriving a contradiction from this. By contrast, there's lots of ways to do natural deduction proofs, not just assuming what you're trying to show is false.

**Comment by Finn1928** [comment]
My derivation didn't copy over very well. You can see it better here: https://github.com/Finn1928/PHI-696-Finn-/tree/main/Project-1

**Comment by Jvonderhbuff** [comment]
Hi Olivia,

I will say ahead of time that I can't help much with 4. As is, I don't really feel confident enough in ALC to make a specific call on the correctness of interpretations there beyond the fact that we can't have variables in the syntax (x,y,z, etc.)

With that said, here's what I saw (assuming the file with all of the commits is the current version because GitHub's UI is impenetrable):

2: It's good to show your process like that but it would help to make you final answer a bit clearer for readability. Separate it out by a few lines or just mark it as "conclusion" or something like that. (a) Is especially bad for that as it reads as though the full equality statement is your final answer when I take it to just be what is to the right of the equals sign.

3:  You need additional parentheses to carry the existential quantifier (∃) across all of your uses of x, y, and z. Also, you shouldn't use that quantifier for the relationship (P) in this format. Formatting your interpretation should look something like this ∃(x)∃(y)∃(z)(formula involving x, y, and z).

Also you don't need the universal quantifier before what you are defining imo. It doesn't make a difference but seems unnecessary. On a similar note, the non-identity relationships you establish seem unnecessary. X, y, and z being different things is already established by them being different variables. If we were talking about the same thing we would just say x or one of the other variables again. It doesn't hurt your answer to the best of my knowledge but seems unnecessary.

5: Your answer here seems incomplete on account of 4 being incomplete but I will note that you should be sure to define all constants, variables, and relations with the Abox part of the model.

6: You go too far in your answer to (a) by saying that x "contains" y. That is one type of relationship that could be involved there, but all that is given using first-order quantifiers in that sort of relationship is that there is some relationship between them.

With (a), this would mean that part of an answer would say that "For all things such that they are x, there is something such that it is y that has a certain relationship with all things such as they are x." That would be a laborious version of the second part of (a) (it is maximally correct but saying "all things such that they are" or "something such that it is" is very irritating to write over and over). 

Basically, you are speaking of too specific a relationship with all of these by saying that they "contain" each other when all that is given is that there is a certain relationship between differently quantified variables.

7: You should have some kind of visual example for each of these to make them a graph. Some other people here can talk about how to make a graph like this with Mermaid, but you can just make a graph with the <>^ symbols as arrows indicating the relationships in question and get a successful graph for this.

9: You have nothing here, so I will note that you can actually do these proofs very quickly if you use the negated disjunction and negated conjunction rules. These rules look like the following:

~^: ~(A^B)=~Av~B
~v= ~(AvB)=~A^~B

These rules apply because the truth values of the two parts of each are the same (disjunctions are only false if both parts are false and conjunctions are false if any part of the conjunction is false). 

Using these rules, the only proof that goes on for more than 6 steps will be for (d). What you have to do is to assume the only situation where the conditionals in these laws are false and show that leads to a contradiction. This will mean that your first two steps will be assuming that the first part of the conditional is true and the second part is false. From there, you apply the two rules above alongside the double negation rule (~~A=A), conjunction rule (A^B=A, B), and disjunction rule (AvB=A&~B, ~A^B, and A^B) and you should be able to prove the laws with very short proofs.

I will note that this may involve assuming the truth of some of these laws, but nothing in the question says you cannot use the laws in the proofs themselves and the only difference between proofs using them and proofs not using them is that those without will be much longer (relying on the conjunction and disjunction rules primarily).

For the proofs, you should also know that the proof ends when you find a contradiction with a statement further up the proof. I don't know how familiar you are with these kinds of proofs, but you should be aware that you do not need to go to the basic letters to find contradictions with the ~^ and ~v rules.

**Comment by johnbeve** [comment]
> Also you don't need the universal quantifier before what you are defining imo. It doesn't make a difference but seems unnecessary. 

You do need universal quantifiers before what you're defining. Otherwise, you'll either have a defined relation with implicit universal quantifiers that are disconnected from the right-hand side of your definition, or existentially quantified definitions satisfied by any one pair, but otherwise placing no constraints on other pairs. 

>On a similar note, the non-identity relationships you establish seem unnecessary. X, y, and z being different things is already established by them being different variables. 

Variables may stand for _anything_ in the domain; they may refer to the same elements of the domain. If what you've said here were true, any axiom declaring x=y would be trivially false.  

>~^: ~(A^B)=AvB
~v= ~(AvB)=~A^~B

The first of these isn't even true...~(A^B )= ~Av~B

@Finn1928 Did you see this?

**Comment by Jvonderhbuff** [comment]
> > ~^: ~(A^B)=AvB

I am not sure why this is happening, but that should say ~Av~B but there is some kind of formatting issue which is causing it to come through wrong. Written out that is not A or not B, which has the same truth table as the negated conjunction in question. It says that in the actual text of what I wrote there (I tried to edit the comment before it to fix what I thought was a typo) but it is coming through either with a strikethrough or without the tildes for whatever reason.

**Comment by johnbeve** [comment]
Should I be reviewing this commit or the commit here: https://github.com/johnbeve/PHI-696/pull/30
@oliviahobai @Finn1928 @SydCo99 @Jvonderhbuff @Arachnophobian @dmcnulty27

**Pull request closed without merging**
